### ISSUE TITLE
can't get "hide board view hidden columns" tweak to work

### ISSUE THREAD

**Issue by siastardust** [notion-enhancer/tweaks#16]
hi! i've added the following css code to the tweak section -

/* ========== HIDE BOARD VIEW HIDDEN COLUMNS ========== */
.notion-board-view > [data-block-id] > div:nth-last-child(2),
.notion-board-view > [data-block-id] > div:first-child > div:nth-last-child(2) {
  display: none !important;
}

but instead of hiding the hidden column, my entire table becomes empty:
![screenshot](https://user-images.githubusercontent.com/92759585/137808819-5d7357a0-327a-477c-8b5f-aaf04f9af3a6.png)

if i switch it back to the default view, all of the information is still there, but disappears as soon as i switch it back to board view. conversely, another table on another page still shows all of the information, but the "hidden column" is still there. my knowledge of coding and css is pretty basic, so there could just be something going completely over my head, but i'm pretty sure i did everything correctly. help!

**Comment by dragonwocky** [comment]
@siastardust I missed a bit sorry, edited/updated it, try again now

**Comment by siastardust** [comment]
@dragonwocky still no luck unfortunately :/ i wonder if maybe i'm just doing something wrong - but i checked out a youtube tutorial and from what i can tell i'm doing it correctly. i really appreciate your help!

**Comment by dragonwocky** [comment]
oops, you're all good, I had gotten rid of the actual hidden columns but not the "hidden columns" title - try it now
