### ISSUE TITLE
Remove arrows on linked pages and databases - Tweak Not Working

### ISSUE THREAD

**Issue by carloshenrgin** [notion-enhancer/tweaks#26]
![imagem_2021-12-02_231000](https://user-images.githubusercontent.com/80416070/144532836-f78f512e-cb24-410b-abae-01ccb411583a.png)

I don't know why this tweak doesn't work for me. I tried to fix it by myself but I failed to do so.

**Comment by dragonwocky** [comment]
this repository is being archived & all issues are being closed in favour of a new tweaks page on the notion-enhancer website (coming soon)
