### ISSUE TITLE
developer documentation - 404 not found - wider previews?

### ISSUE THREAD

**Issue by Excoss** [notion-enhancer/tweaks#27]
Hey all,
I am looking to get the wider previews CSS tweak.
It says it's been added to the Developer documentation, however that page now leads to a 404.

Anyone got any ideas?

**Comment by Excoss** [comment]
Found by going to threw legacy documentation. 

Here is a link if anyone comes here looking for this.
https://github.com/notion-enhancer/desktop/blob/b5043508d91df76f145f0f48c2c63d7dd1c27543/STYLING.md

**Comment by dragonwocky** [comment]
this repository is being archived & all issues are being closed in favour of a new tweaks page on the notion-enhancer website (coming soon)
