### ISSUE TITLE
The width of the column in the first line does not change

### ISSUE THREAD

**Issue by Khilkov** [notion-enhancer/tweaks#5]
![image](https://user-images.githubusercontent.com/46132242/117483077-edbfd400-af6d-11eb-909d-d30683d9cd5f.png)
The width of the column in the first line does not change, but the others have changed. What could be the problem?

**Comment by eshill** [comment]
`
/* ========== TABLE COLUMNS BELOW 100PX ========== */
[data-block-id^='31803fdb-da52-4aa9-8f88-015b97ba7c7f']
  > [style^='display: flex; position: absolute; background: rgb(47, 52, 55); z-index: 82; height: 33px; color: rgba(255, 255, 255, 0.6);']
  > div:nth-child(1)
  > div:nth-child(1)
  > div:nth-child(1),
[data-block-id^='31803fdb-da52-4aa9-8f88-015b97ba7c7f']
  > [style^='position: relative; min-width: calc(100% - 192px);']
  > [data-block-id]
  > div:nth-child(1), 
[data-block-id^='31803fdb-da52-4aa9-8f88-015b97ba7c7f'] > div:nth-child(5) > div:nth-child(1) {
  width: 32px !important;
}
[data-block-id^='31803fdb-da52-4aa9-8f88-015b97ba7c7f']
  [style^='position: absolute; top: 0px; left: 0px; pointer-events: none;']:not(.notion-presence-container) {
  display: none;
}
`

**Comment by dragonwocky** [comment]
this repository is being archived & all issues are being closed in favour of a new tweaks page on the notion-enhancer website (coming soon)
