### ISSUE TITLE
"Remove "Type '/' for commands"" tweak not working

### ISSUE THREAD

**Issue by albertopasqualetto** [notion-enhancer/tweaks#6]
[It](https://github.com/notion-enhancer/tweaks/blob/1f364adac9366a8bf805d69836d36bb43721aa2f/tweaks/remove%20type%20for%20commands.md) doesn't behave as it should do.

**Comment by Adambl4** [comment]
Did not test if for a long time. What is the problem with it?

**Comment by albertopasqualetto** [comment]
The string is still visible.

Il giorno lun 28 giu 2021 alle ore 16:14 Adambl4 ***@***.***>
ha scritto:

**Comment by forrest-herman** [comment]
I can confirm this doesn't work

**Comment by forrest-herman** [comment]
I changed the code to be: 

[contenteditable]::before {
    display: none !important;
}

And it seems to now work as expected. I will update if I have an adverse effects!

**Comment by dragonwocky** [comment]
oh, missed this, give this a go:
```css
[contenteditable]:empty:after {
  content: ' ' !important;
}
```

**Comment by albertopasqualetto** [comment]
This one is working, but it also removes the writing cursor is hidden.

**Comment by dragonwocky** [comment]
@albertopasqualetto that's a separate bug caused by tabs.

**Comment by albertopasqualetto** [comment]
@dragonwocky ok, so thanks, but the sum of the 2 things makes it hard to see where I am writing.
I made a pull request with your new code (#11)
