### ISSUE TITLE
Tweak for "Hide '+ New' Gallery Button" and "Hide '+ New' Table Row" not working

### ISSUE THREAD

**Issue by Red-Verlin** [notion-enhancer/tweaks#7]
The buttons remain. I tested out some other tweaks to make sure it's not me doing something wrong, but other tweaks seem to be working fine. It's mainly the Gallery Button tweak I'm trying to get to work.

**Comment by DrenSkywalker** [comment]
Hi! Try like this: 

```
/* ========== HIDE THE '+ NEW' GALLERY BUTTON ========== */
.notion-gallery-view
  .notion-selectable.notion-collection_view-block
  div
  > [role="button"],
.notion-gallery-view
  .notion-selectable.notion-collection_view_page-block
  div
  > [role="button"] {
  display: none !important;
}
```

**Comment by khanhtuongle** [comment]
> Hi! Try like this for the Gallery Button:
> 
> ```css
> /* ========== HIDE THE '+ NEW' GALLERY BUTTON ========== */
> .notion-gallery-view
>   .notion-selectable.notion-collection_view-block
>   div
>   > [role="button"],
> .notion-gallery-view
>   .notion-selectable.notion-collection_view_page-block
>   div
>   > [role="button"] {
>   display: none !important;
> }
> ```

thank you so much

**Comment by dragonwocky** [comment]
thanks @DrenSkywalker, i've updated the .md
@Red-Verlin the hide +new table row works according to my testing? closing this for now, but if you're still having issues just send another reply and I'll have a look
